### PR TITLE
Add generator feature to disable line splitting

### PR DESCRIPTION
**Pull request by vjkoskela**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds good!

Before I can merge the contribution (which I'll be happy to do ASAP) I just need one thing, filled Contributor License Agreement (CLA) from

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

(unless we already have one? Apologies if so, we are getting steady stream so occasionally I forget)

All that is needed is to fill, sign, print and scan it, then send to `info` at fasterxml dot com.
And once we have a copy, it's valid for any and all contributions for Jackson projects.

Thank you again!

**Comment by vjkoskela** [comment]
Not a problem as far as I am concerned. Unfortunately, I need to just get
the good old stamp of approval from our legal department. Unfortunately,
this could take a few days at best.

Cheers,
Ville

On Thu, Mar 26, 2015 at 5:46 PM, Tatu Saloranta <notifications@github.com>
wrote:

> Sounds good!
>
> Before I can merge the contribution (which I'll be happy to do ASAP) I
> just need one thing, filled Contributor License Agreement (CLA) from
>
> https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf
>
> (unless we already have one? Apologies if so, we are getting steady stream
> so occasionally I forget)
>
> All that is needed is to fill, sign, print and scan it, then send to info
> at fasterxml dot com.
> And once we have a copy, it's valid for any and all contributions for
> Jackson projects.
>
> Thank you again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-dataformat-yaml/pull/32#issuecomment-86774246>
> .
>



-- 
*Ville Koskela*
Software Engineer

505 5th Ave S, Suite 310, Seattle, WA 98104
Desk: 206-357-3354
Mobile: 206-973-6877
Groupon
<http://www.google.com/url?q=http%3A%2F%2Fwww.groupon.com%2F&sa=D&sntz=1&usg=AFrqEzcC80FkwsjyolWTKAH1sZ9yU2t0xg>
 II Grouponworks
<http://www.google.com/url?q=http%3A%2F%2Fwww.grouponworks.com%2F&sa=D&sntz=1&usg=AFrqEzdLBm3Dql75wz1BTY0mA30ov3RnWg>

**Comment by cowtowncoder** [comment]
@vjkoskela Understood -- although it is possible to just sign personal CLA, unless work being is within context of your job (during work time, using employer's systems or within scope of company's business is the usual "triple requirement"). I have no idea about context, so I just mention this for sake of completeness.

**Comment by vjkoskela** [comment]
Thanks. Yes, the work I am contributing in this case is within the context
of my job at Groupon.

On Tue, Mar 31, 2015 at 11:22 AM, Tatu Saloranta <notifications@github.com>
wrote:

> @vjkoskela <https://github.com/vjkoskela> Understood -- although it is
> possible to just sign personal CLA, unless work being is within context of
> your job (during work time, using employer's systems or within scope of
> company's business is the usual "triple requirement"). I have no idea about
> context, so I just mention this for sake of completeness.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-dataformat-yaml/pull/32#issuecomment-88197278>
> .
>



-- 
*Ville Koskela*
Software Engineer

505 5th Ave S, Suite 310, Seattle, WA 98104
Desk: 206-357-3354
Mobile: 206-973-6877
Groupon
<http://www.google.com/url?q=http%3A%2F%2Fwww.groupon.com%2F&sa=D&sntz=1&usg=AFrqEzcC80FkwsjyolWTKAH1sZ9yU2t0xg>
 II Grouponworks
<http://www.google.com/url?q=http%3A%2F%2Fwww.grouponworks.com%2F&sa=D&sntz=1&usg=AFrqEzdLBm3Dql75wz1BTY0mA30ov3RnWg>

**Comment by cowtowncoder** [comment]
That makes sense. I know some engineers from Groupon, very competent folks. And I'd expect there are reasonable procedures for clearing up OSS contributions.

**Comment by vjkoskela** [comment]
I saw your other email. I'll take this up with Brian if it hits a wall with
legal. Unfortunately, those procedures are not as clear when it comes to
CLAs.

On Tue, Mar 31, 2015 at 1:32 PM, Tatu Saloranta <notifications@github.com>
wrote:

> That makes sense. I know some engineers from Groupon, very competent
> folks. And I'd expect there are reasonable procedures for clearing up OSS
> contributions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-dataformat-yaml/pull/32#issuecomment-88235493>
> .
>



-- 
*Ville Koskela*
Software Engineer

505 5th Ave S, Suite 310, Seattle, WA 98104
Desk: 206-357-3354
Mobile: 206-973-6877
Groupon
<http://www.google.com/url?q=http%3A%2F%2Fwww.groupon.com%2F&sa=D&sntz=1&usg=AFrqEzcC80FkwsjyolWTKAH1sZ9yU2t0xg>
 II Grouponworks
<http://www.google.com/url?q=http%3A%2F%2Fwww.grouponworks.com%2F&sa=D&sntz=1&usg=AFrqEzdLBm3Dql75wz1BTY0mA30ov3RnWg>

**Comment by cowtowncoder** [comment]
Matching functionality implemented as #35, closing this pull request.

**Pull request closed without merging**
